# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WeatherApp2
  pod 'MBProgressHUD', '~> 1.1.0'
  target 'WeatherApp2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherApp2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
